import { ParticipantsType } from "../redux/Participants";

export const dummyParticipants: ParticipantsType[] = [
  {
    userId: "u1",
    userName: "Abhishek",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=1",
    email: "abhishek@example.com",
  },
  {
    userId: "u2",
    userName: "Ravi Kumar",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=2",
    email: "ravi@example.com",
  },
  {
    userId: "u3",
    userName: "Sneha Reddy",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=3",
    email: "sneha@example.com",
  },
  {
    userId: "u4",
    userName: "Arjun Patel",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=4",
    email: "arjun@example.com",
  },
  {
    userId: "u5",
    userName: "Priya Sharma",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=5",
    email: "priya@example.com",
  },
  {
    userId: "u6",
    userName: "Rahul Verma",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=6",
    email: "rahul@example.com",
  },
  {
    userId: "u7",
    userName: "Anjali Mehta",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=7",
    email: "anjali@example.com",
  },
  {
    userId: "u8",
    userName: "Kiran Rao",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=8",
    email: "kiran@example.com",
  },
  {
    userId: "u9",
    userName: "Vikram Singh",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=9",
    email: "vikram@example.com",
  },
  {
    userId: "u10",
    userName: "Neha Gupta",
    isMuted: 0,
    isVideoOn: 0,
    imageUrl: "https://i.pravatar.cc/150?img=10",
    email: "neha@example.com",
  },
];